# Generated by Django 5.1.6 on 2026-10-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Official name of the organization (e.g., 'City Hope Shelter').", max_length=255, unique=True)),
                ('org_type', models.CharField(choices=[('SHELTER', 'Emergency Shelter'), ('FOOD_BANK', 'Food Bank / Pantry'), ('NGO', 'Non-Governmental Organization')], default='FOOD_BANK', help_text="Classification defining the organization's primary community function.", max_length=20)),
                ('address', models.TextField(help_text='Physical facility address or headquarters location.')),
                ('contact_email', models.EmailField(help_text='Primary email address for administrative and logistics contact.', max_length=254)),
                ('contact_phone', models.CharField(help_text='Direct phone line for coordination and emergency dispatch.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Audit timestamp indicating when this organization record was created.')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
            },
        ),
    ]
