# Generated by Django 5.1.6 on 2026-10-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the inventory category (e.g., 'Non-Perishable Food', 'Baby Care').", max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Detailed description of goods falling under this category.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Common name of the item (e.g., 'Long Grain White Rice', 'Bottled Water 500ml').", max_length=200)),
                ('unit_of_measure', models.CharField(help_text="Standard unit used to track this item (e.g., 'kg', 'pieces', 'liters', 'boxes').", max_length=50)),
                ('is_perishable', models.BooleanField(default=False, help_text='Designates whether the item requires climate control or expires rapidly.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this item definition was created in the system.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this item definition was last modified.')),
                ('category', models.ForeignKey(help_text='Category classification for this item. PROTECT prevents accidental orphan items.', on_delete=django.db.models.deletion.PROTECT, related_name='items', to='inventory.category')),
                ('organization', models.ForeignKey(help_text='The shelter or food bank managing this inventory item definition.', on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['organization', 'name'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'name'), name='unique_item_per_organization')],
            },
        ),
    ]
