# Generated by Django 5.1.6 on 2026-10-02 13:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_name', models.CharField(blank=True, help_text='Name of the donor or contributing group (leave blank if anonymous).', max_length=255)),
                ('donor_contact', models.CharField(blank=True, help_text='Optional contact information (email, phone, or address) for receipts.', max_length=255)),
                ('date_received', models.DateField(default=django.utils.timezone.now, help_text='Calendar date when the donation was physically handed over.')),
                ('notes', models.TextField(blank=True, help_text='Optional intake details, condition of packaging, or vehicle info.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='System audit timestamp when this record was logged.')),
                ('organization', models.ForeignKey(help_text='The organization that received this donation.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(help_text='Staff or volunteer member who processed this intake.', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
                'ordering': ['-date_received', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('DONATION_IN', 'Donation Received (In)'), ('MANUAL_ADJUSTMENT_IN', 'Manual Adjustment (In)'), ('MANUAL_ADJUSTMENT_OUT', 'Manual Adjustment (Out)'), ('DISTRIBUTION_OUT', 'Distribution to Client (Out)')], help_text='Nature of the stock movement.', max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive quantity moved in this transaction.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('note', models.TextField(blank=True, help_text='Explanation for adjustments, damages, or discrepancies (mandatory for manual adjustments).')),
                ('expiry_date', models.DateField(blank=True, help_text='Expiration date (applicable only if the item is marked perishable).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Exact audit timestamp of transaction.')),
                ('donation', models.ForeignKey(blank=True, help_text='Linked donation event if this transaction originated from a donation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='inventory.donation')),
                ('inventory_item', models.ForeignKey(help_text='The catalog item being added or deducted.', on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to='inventory.inventoryitem')),
                ('organization', models.ForeignKey(help_text='The organization owning the item and facility.', on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='organizations.organization')),
                ('recorded_by', models.ForeignKey(help_text='User who authorized or performed this stock action.', on_delete=django.db.models.deletion.PROTECT, related_name='recorded_stock_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Transaction',
                'verbose_name_plural': 'Stock Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
