# Generated by Django 5.1.6 on 2026-10-02 17:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_donation_stocktransaction'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum stock level before alerting staff to reorder or request donations.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='DistributionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(help_text='Name of the individual, family, shelter client, or community program receiving items.', max_length=255)),
                ('recipient_contact', models.CharField(blank=True, help_text='Optional phone number, email, or emergency contact info.', max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Fulfillment'), ('REJECTED', 'Rejected'), ('FULFILLED', 'Fulfilled')], default='PENDING', help_text='Current state in the approval and fulfillment lifecycle.', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this distribution request was submitted.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when an administrator approved or rejected the request.', null=True)),
                ('notes', models.TextField(blank=True, help_text='Context regarding recipient needs, rejection reasons, or partial fulfillment notes.')),
                ('organization', models.ForeignKey(help_text='The organization whose inventory is being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='distribution_requests', to='organizations.organization')),
                ('requested_by', models.ForeignKey(help_text='Staff or volunteer who submitted this request on behalf of the recipient.', on_delete=django.db.models.deletion.PROTECT, related_name='distribution_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Administrator who approved or rejected this request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_distribution_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Distribution Request',
                'verbose_name_plural': 'Distribution Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='distribution_request',
            field=models.ForeignKey(blank=True, help_text='Linked distribution request if this transaction represents an outbound distribution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_transactions', to='inventory.distributionrequest'),
        ),
        migrations.CreateModel(
            name='DistributionRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=2, help_text='Quantity requested for the recipient.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity_fulfilled', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Actual quantity fulfilled/dispatched.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('distribution_request', models.ForeignKey(help_text='The parent distribution request.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.distributionrequest')),
                ('inventory_item', models.ForeignKey(help_text='The item to be distributed.', on_delete=django.db.models.deletion.PROTECT, related_name='distribution_items', to='inventory.inventoryitem')),
            ],
            options={
                'verbose_name': 'Distribution Request Item',
                'verbose_name_plural': 'Distribution Request Items',
                'ordering': ['inventory_item__name'],
                'constraints': [models.UniqueConstraint(fields=('distribution_request', 'inventory_item'), name='unique_item_per_distribution_request')],
            },
        ),
    ]
