# Generated by Django 5.1.6 on 2026-10-02 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventoryitem_reorder_threshold_distributionrequest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donor_user',
            field=models.ForeignKey(blank=True, help_text='Optional link to a registered User account with the DONOR role.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
